apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-unsigned-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: "{{ _internal_app_namespace }}"
    server: 'https://kubernetes.default.svc'
  project: default
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  source:
    path: gitops/inventory/overlays/fail
    repoURL: >-
      {{ _internal_gitea_repo_devsecops_url }}
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true