bases:
- ../../base

patchesStrategicMerge:
- delete-application-globex-unsigned.yaml

patches:
- target:
    kind: Application
    name: globex
  patch: |-
    - op: replace
      path: /spec/source/path
      value: gitops/application/globex/overlays/prod