apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: app-globex-ui-unsigned-binding
spec:
  params:
  - name: imageRepo
    value: "{{ _internal_image_repo }}"
  - name: manifestRepo
    value: "{{ _internal_manifest_repo }}"
  - name: manifestFile
    value: "{{ _internal_manifest_file_fail }}"
  - name: tlsVerify
    value: "true"