kind: Secret
apiVersion: v1
metadata:
  name: cosign-secret
data:
  cosign.key: "{{ _internal_cosign_key }}"
  cosign.password: "{{ _internal_cosign_password }}"
  cosign.pub: "{{ _internal_cosign_pub }}"
type: Opaque
