apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign-sign
spec:
  params:
  - default: docker.io/sonarsource/sonar-scanner-cli:latest
    name: image
    type: string
  - default: cosign-secret
    name: cosignSecret
    type: string
  - default: redhat-registry-secret
    name: registrySecret
    type: string
  results:
  - description: The signature of the image
    name: tlogIndex
  steps:
  - env:
    - name: COSIGN_KEY
      valueFrom:
        secretKeyRef:
          key: cosign.key
          name: $(params.cosignSecret)
    - name: COSIGN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: cosign.password
          name: $(params.cosignSecret)
    - name: REGISTRY_SECRET
      valueFrom:
        secretKeyRef:
          key: .dockerconfigjson
          name: $(params.registrySecret)
    image: quay.io/redhat-gpte/cosign
    name: sign-image
    script: |
      set -x

      cd /tmp

      echo "${COSIGN_KEY}" > ./cosign.key
      echo "${REGISTRY_SECRET}" > /home/cosign/.docker/config.json
      COSIGN_EXPERIMENTAL=1 COSIGN_PASSWORD=$COSIGN_PASSWORD cosign sign --key cosign.key --yes $(params.image)
      cosign download signature $(params.image) --output-file /workspace/signature.sig
  - image: stedolan/jq
    name: extract-tlog
    script: |
      set -x
      jq '.Bundle.Payload.logIndex' /workspace/signature.sig > $(results.tlogIndex.path)
  workspaces:
  - name: signature
