apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign-sign
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-cosign-conf: secret/cosign/config
    vault.hashicorp.com/agent-inject-template-cosign-conf: |
      {{ with secret "secret/cosign/config" -}}
        export COSIGN_KEY="{{ .Data.data.cosign_key }}"
        export COSIGN_PASSWORD="{{ .Data.data.cosign_password }}"
      {{- end }}
    vault.hashicorp.com/role: cosign
spec:
  params:
  - default: docker.io/sonarsource/sonar-scanner-cli:latest
    name: image
    type: string
  - default: secret/data/cosign
    name: vaultSecretPath
    type: string
  - default: redhat-registry-secret
    name: registrySecret
    type: string
  results:
  - description: The signature of the image
    name: tlogIndex
  steps:
  - image: openshift/origin-cli
    name: get-vault-secret
    script: >
      set -x

      source /vault/secrets/cosign-conf

      echo "${COSIGN_KEY}" > /workspace/cosign.key

      echo "${COSIGN_PASSWORD}" > /workspace/cosign.password
  - env:
      - name: REGISTRY_SECRET
        valueFrom:
          secretKeyRef:
            key: .dockerconfigjson
            name: $(params.registrySecret)
    image: quay.io/redhat-gpte/cosign
    name: sign-image
    resources: {}
    script: >
      set -x

      echo "${REGISTRY_SECRET}" > /home/cosign/.docker/config.json

      COSIGN_EXPERIMENTAL=1 COSIGN_PASSWORD=$(cat /workspace/cosign.password)
      cosign sign --key /workspace/cosign.key --yes $(params.image)

      cosign download signature $(params.image) --output-file
      /workspace/signature.sig
  - image: stedolan/jq
    name: extract-tlog
    script: |
      set -x
      jq '.Bundle.Payload.logIndex' /workspace/signature.sig > $(results.tlogIndex.path)
  workspaces:
  - name: signature
