apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    template: postgresql-persistent-template
  name: sonardb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi