apiVersion: v1
data:
  database-name: c29uYXI=
  database-password: UGhFS05HMFJlamJxSnQyOA==
  database-user: dXNlcmRseHd1ZDQ3
kind: Secret
metadata:
  labels:
    app: sonarqube
    template: postgresql-persistent-template
  name: sonardb
type: Opaque